### ISSUE TITLE
antd 세팅 문의

### ISSUE THREAD

**Issue by Hyun2** [grotesq/codelab-next-js-3rd#1]
언제나 좋은 강의 감사합니다!

오늘 강의 중에 antd 설치하고, _app.js에서 css import해서 사용하는 거랑
아래 링크처럼 세팅해서 사용하는 거랑 어떤 차이가 있나요?

https://dev.to/burhanuday/using-ant-design-with-nextjs-custom-variables-for-ant-design-57m5

**Comment by unk** [comment]
좋은 질문 감사합니다!

아래 링크의 경우에는 ant design을 사용하되, 기본 색상이나 공통 radius 값 등을 재정의 해서 커스텀 테마처럼 만들어서 사용하는 경우에 대한 예시를 보여주고 있습니다. 작업한 파일들을 보면

`/styles/antd.less`
이 파일은 앤트 디자인 소스 파일인 `~antd/dist/antd.less` 를 로드하고 `@primary-color` 등을 재정의 하는 내용을 담고 있습니다.

`/pages/_app.js`
여기서는 프로젝트 내의 파일 `/styles/antd.less` 를 로드하고 있습니다.

제가 강의중 진행한 내용은 커스텀 테마에 대한 부분은 필요하지 않았기 때문에,
소스 파일인 less 가 아닌 빌드된 css 파일을 바로 로드해서 사용했습니다.

다른 궁금하신 점이 생기시면 무엇이든 질문해주세요 :)
감사합니다.
