### ISSUE TITLE
[next.js 2강]immer, immutable 질문 드립니다.

### ISSUE THREAD

**Issue by DavidYang2149** [grotesq/codelab-next-js-3rd#2]
안녕하세요.
Next.js 2강을 듣던 중 immer, immutable에 대한 궁금증이 생겨 질문을 드립니다.

동영상에서 약 1:35:00 부터 [immutable](https://immutable-js.github.io/immutable-js)에 대해서 설명을 해주셨는데요.
실제 코드상에서 입력할 때는 **npm install immer**로 되었는데, npm에서 **npm install immutable**도 존재하는 것을 확인했습니다.

**immer**, **immutable** 두개가 **서로 같은 것인지** 궁금합니다.
**다르다면 어떤 부분이 차이가 있는지**도 알고 싶습니다.

감사합니다.

**Comment by unk** [comment]
질문이 광범위 해서 구체적으로 다 말씀드리기는 어렵고 대략적인 내용과 추가 정보를 찾아보실 수 있는 키워드, 링크 등을 드려야겠군요.

결론적으로 목적은 같지만 그걸 구현하는 방향은 다른, 서로 다른 라이브러리입니다.

immutable.js 는 자바스크립트 기본 객체를 사용하지 않고 Object 대신 Map, Array 대신 List 를 사용합니다.
데이터의 변경을 반드시 .set() 함수 등을 통해 수행하도록 설계 되어 있습니다.
https://immutable-js.github.io/immutable-js/

Immer 는 자바스크립트 기본 객체를 사용하고, Proxy 객체를 이용하는 함수를 통해 업데이트 하도록 되어 있습니다.
https://immerjs.github.io/immer/docs/introduction

```js
// Immutable.js
const { Map } = require('immutable');
const map1 = Map({ a: 1, b: 2, c: 3 });
const map2 = map1.set('b', 50);
map1.get('b') + " vs. " + map2.get('b'); // 2 vs. 50
```

```js
// Immer
const produce = require( 'immer' );
const map1 = { a: 1, b: 2, c: 3 };
const map2 = produce(map1, draft => {
  draft.b = 50;
});
map1.b + " vs. " + map2.b; // 2 vs. 50
```

다른 궁금하신 점이 생기시면 무엇이든 질문해주세요 :)
감사합니다.

**Comment by DavidYang2149** [comment]
제가 원했던 내용입니다.
빠른 답변 감사합니다! ☺️
